apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-lag-scaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-lag-scaler.labels" . | nindent 4 }}
