apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-worker
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-worker
  template:
    metadata:
      labels:
        app: orders-worker
    spec:
      containers:
        - name: worker
          image: nginx:1.25
